name: lltoken_sensor
version: dev
slug: enviroment
description: "this is an addon to collect indicator of enviroment"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
  - bmp180
  - bmp280
  - sht31
  - sht45
  - oxygen
options:
  addr-bmp: none
  addr-sht: none
  addr-oxy: none
  base_url:
    required: true
  token:
    required: true
  ssl: false
  bmp180: false
  bmp280: false
  sht31: false
  sht45: false
  oxygen: false
schema:
  base_url: str?
  token: str?
  bmp180: bool
  bmp280: bool
  sht31: bool
  sht45: bool
  oxygen: bool
  addr-bmp: list(0x76|0x77)
  addr-sht: list(0x44|0x45)
  addr-oxy: list(0x70|0x71|0x72|0x73)
devices:
  - "/dev/i2c-5:rwm"
